// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLpZ-Syuf0Ht4eWROSne2PQ3MijuRVyRE',
    appId: '1:682580151127:web:32071a2b13e03dd5e1cc12',
    messagingSenderId: '682580151127',
    projectId: 'time-tracker-flutter-2ff6d',
    authDomain: 'time-tracker-flutter-2ff6d.firebaseapp.com',
    storageBucket: 'time-tracker-flutter-2ff6d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKclGTg0w816ofuHbq7vwQaFlIDLaiQN8',
    appId: '1:682580151127:android:5225a25951ce385ce1cc12',
    messagingSenderId: '682580151127',
    projectId: 'time-tracker-flutter-2ff6d',
    storageBucket: 'time-tracker-flutter-2ff6d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIjRk1MfcW_8kkHWcpBgPfONcEng4xHGc',
    appId: '1:682580151127:ios:e31d533985c9fac9e1cc12',
    messagingSenderId: '682580151127',
    projectId: 'time-tracker-flutter-2ff6d',
    storageBucket: 'time-tracker-flutter-2ff6d.appspot.com',
    androidClientId: '682580151127-vort75kmembj5qrf2sig67cqn4u8mplt.apps.googleusercontent.com',
    iosClientId: '682580151127-opf9rj4ig71501vd4l8lohlvka3h07hp.apps.googleusercontent.com',
    iosBundleId: 'com.example.timeTrackerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIjRk1MfcW_8kkHWcpBgPfONcEng4xHGc',
    appId: '1:682580151127:ios:e31d533985c9fac9e1cc12',
    messagingSenderId: '682580151127',
    projectId: 'time-tracker-flutter-2ff6d',
    storageBucket: 'time-tracker-flutter-2ff6d.appspot.com',
    androidClientId: '682580151127-vort75kmembj5qrf2sig67cqn4u8mplt.apps.googleusercontent.com',
    iosClientId: '682580151127-opf9rj4ig71501vd4l8lohlvka3h07hp.apps.googleusercontent.com',
    iosBundleId: 'com.example.timeTrackerApp',
  );
}
